### ISSUE TITLE
トーナメントを実装する

### ISSUE THREAD

**Issue by massahito** [ShotaTanemura/ft_transcendence#102]
## As Is
- 2人がルームに入ると即試合が開始される。
## To Be
- 2, 4人でのトーナメント対戦ができる。
## 目標とする処理の流れ
1. ルームを作成するユーザーが、2人か4人のルームを特定のroomIDで作成する
2. ルームに参加するユーザーは、roomIDを指定して、roomに入り、人数が集まるまで待たされる。
3. 人数が集まった段階で、トーナメントがスタートする。(トーナメントの情報はtournamentmanagerが管理する)
4. 試合前と試合終了後にtournamentmanagerから情報を取得、更新する。
5. トーナメント終了時には、優勝者を称える画面を出力し、サーバー側ではroommanager, ソケット及びその他のリソースを破壊する。

## roomstate (roommanagerが持つべきstate)
- Not_All_Participants_Connected (参加者が全員揃っていない状態)
- Waiting_For_Participants_Approve_Roomt (すべての参加者がroomを承認していない状態)
- Display_Tournament (トーナメントを表示している状態)
- In_Game (2人の参加者がゲーム中である状態)
- Tournament_Finished(すべての処理が終わり、破壊待ちの状態)

### なぜroomstateを持つ必要があるのか？
- ユーザーは常に同じconsumerに対して接続するのにたいして、トーナメントの進捗や、試合中か否かによってサーバー側での処理を変更する必要があるから。

## tournamentmanagerの役割
- roommanagerに次の対戦カードを提示、またはトーナメントの終了を通知する
- トーナメントのスコア試合結果を保持する

## ブラウザのリロードによる再接続への対処
- 再接続時にいまroomがどのステートなのかを送ることでspaでもクライアントで何(どのページ)を描画すればいいのか判断できそう。
- ソケットその接続時にユーザーがroomに入っていたのかどうかを判断する(例えばredisにユーザーのuuidとroomIDの対応表を保存するなどして)必要がある。

## 積み残し
- connect時に任意のメッセージを贈りたいが、それは可能?
    - connect時にroomの状態を取得するためのリクエストを送れば行ける
- サーバーからソケットを閉じるときに、クライアント側でそれが異常終了か正常終了かどうやって見分けるのか？
    - 異常終了の際に、クローズする前にエラーメッセージをそうしんする。
- roomのstateが変わるたびにクライアントに通知するといいかも、とういうより、画面遷移が必要な場合ってだいたいクライアント側でも変更があるので、その切り替えを揃えたほうが見やすいかも

**Comment by ghost** [comment]
## TournamentManagerのすること
- 作成時
    - 参加者が全員揃った段階で、参加者のlistを受け取る
    - シャッフルして、その順番でトーナメントの対戦カードを作成する。
    - 対戦カードにはそれぞれの参加者と、それぞれのスコア、勝敗などを記録する
- 実行時
    - 試合の直前に次の対戦カードを取得する。もし、優勝者が決定していた場合はその旨を示す何かしらを返す。

**Comment by ghost** [comment]
## 2人のトーナメントを作成する
- ホスト、ゲストの概念は持ち込まず、ユーザーの参加はこれまでのやり方で一連の流れを実装する
### 処理の流れ
1. ユーザーの参加 (実装済み)
2. トーナメント開始 (実装済み)
3. トーナメント表示 (今回実装する)
4. ゲーム開始 (実装済み)
5. 結果表示 (今回実装する)

**Comment by ghost** [comment]
## ホストとゲストの概念を導入する
- pong-gameを実行する際に、roomをホストするか、ゲストとして、ルームに参加するかを選べるようにする

### ホストとゲストの違い
- ホストはroomが空いているかを確認し、空いていれば、roomを作成する
- ゲストはroomがあるかを確認し、roomがあり、参加できる状況(トーナメント開始前)であれば、roomに参加する

### ホストとゲストをどのように区別するか
- websocketのエンドポイントだけ分けて、consumerは共通のものを使用する
