### ISSUE TITLE
ponggameの描画をレスポンシブデザインにする

### ISSUE THREAD

**Issue by massahito** [ShotaTanemura/ft_transcendence#103]
- 後日記載
※8/17日追記
# canvasをレスポンシブにする
- 多くの実装では、canvasの親にタグを作成し、そのタグのサイズをレスポンシブルにして、そのサイズに合わせてjsでcanvasの大きさを決めている。※1, 2
    - おそらく、canvasのサイズはcssで指定できないため。
- window.onresizeのイベントハンドラを使って、ウィンドウのリサイズ時に、canvasも再描画できる。※2
- 中の球やパドルの大きさや位置もcanvasの大きさに合わせて修正してあげる必要がある。

##  参考
1. [Qiita, canvasのレスポンシブ対応](https://qiita.com/wannabe/items/c66ff17edac4c959cad6)
2. [hatenablog, Canvasのレスポンシブ対応](https://shinimae.hatenablog.com/entry/2016/09/29/193858)

**Comment by ghost** [comment]
時間の都合上対応しないことを決定
