### ISSUE TITLE
ponggameの試合結果をdbに保存し、マイページからみれるようにする。

### ISSUE THREAD

**Issue by massahito** [ShotaTanemura/ft_transcendence#104]
- 後日記載

**Comment by ghost** [comment]
## テーブルを洗い出す
- Userテーブル
- Room履歴テーブル
- 対戦履歴テーブル

## カラムを洗い出す
- Userテーブル
	- uuid (PK)
	- name
	- email
- Roomテーブル
	- roomid
	- create-at
	- Winner (FK) ON UPDATE CASCADE ON DELETE SET NULL

- 対戦履歴ID
	- Room(FK) ON UPDATE RISTRICT ON DELETE SET NULL
	- Player1(FK) ON UPDATE CASCADE ON DELETE SET NULL
	- Player2(FK) ON UPDATE CASCADE ON DELETE SET NULL
	- Player1-score
	- Player2-score
	- Winner(FK) ON UPDATE CASCADE ON DELETE SET NULL
## 参考
- [Qiita, データベース（RDB）設計の進め方！](https://qiita.com/ryota_i/items/294281b57cc9783bf2c1)

**Comment by ghost** [comment]
[202fe20](https://github.com/ShotaTanemura/ft_transcendence/commit/202fe204eb27a3c8fa5d1bdcbf8c9f0764e07f2c)でmodelは作成したが、積み残しがある。

### 積み残し
- MatchInfoが何回戦のどの試合かわからない。
    - tournamentの形式を保存していないため、MatchInfoからトーナメントの再構築ができない。
- MatchInfoのwinnerの値が入っていない
    - winnerにplayer1, player2どちらかしか入らないようなmodelの定義のしかたがわからない。
- modelのクエリを作成できていない。
    - userをキーとして、行った試合を取得する。
    - userをキーとして、過去出場したトーナメントを取得する。(user, roomのmapperが必要かも)
