### ISSUE TITLE
他ユーザー検索、friend追加、オンラインステータスの確認

### ISSUE THREAD

**Issue by massahito** [ShotaTanemura/ft_transcendence#142]
Users can add others as friends and view their online status.

**Comment by ghost** [comment]
## 必要な機能
- userの検索
  - フレンド追加ボタンを作成したいから、すでにフレンドかどうかを確認して表示する必要がある
  - オンラインかどうかも確認して表示する必要がある
- userのフレンド追加
  - userの検索から追加する
  - リクエストを受けたユーザーが通知を受け、承認するかどうか決める必要がある
- 通知システムの追加
  - ユーザーがログインしたときやリロードしたときに通知が届くようにする
  - 主にフレンドリクエストの承認、拒否に使う予定
- userのフレンドページ作成
  - サイドバーからフレンド一覧を表示できるようにする
- userのオンラインステータス表示
  - login時にwebsocketをつないで、その記録をredisに書き込む
  - user検索やフレンドページなどでは、redisの結果を取得するapiを用いて、オンラインの判断をする。

**Comment by ghost** [comment]
ユーザーの検索画面は[28b857f](https://github.com/ShotaTanemura/ft_transcendence/pull/151/commits/28b857f9ee6e5caa6ae636be3981d66561523aaa)で作成した。

次はユーザーのフレンド追加を実装する。
## かんたんな要件
- ユーザーの検索画面から、フレンド申請、承認ができる
- 他人のユーザーページから、フレンド申請、承認できる
- フレンド申請されたユーザーは通知からフレンド申請の旨を認識できる
- 通知からフレンド申請を承認できる

ブロック機能はこれらが正しく実装されてから、余裕があれば実装を試みる

## 実装順序
- まず、Pull通知機能を実装する
- 後にフレンド申請、承認機能をついかする。
