### ISSUE TITLE
pong-gameのスタートページを作成する。

### ISSUE THREAD

**Issue by massahito** [ShotaTanemura/ft_transcendence#16]
## 必要な機能
- ユーザ名を入力する機能
- ゲームをスタートさせる機能
- ユーザー数を追加、削除できる機能
- ユーザー名をすべてのコンポーネントで共有できるようにする。

**Comment by ghost** [comment]
まずはユーザ情報を入力するコンポーネントを作成する。
https://maku.blog/p/tdpybmw/
https://qiita.com/stin_dev/items/fc1dfb2458e9564549b7
などを参考にする。
