### ISSUE TITLE
Pong-gameのコア機能を作成する。

### ISSUE THREAD

**Issue by massahito** [ShotaTanemura/ft_transcendence#18]
# コア機能を実装してみる

## 目的
- Django, Python, html, css, javascriptになれること。
- single page applicationの作り方を学ぶこと。

## コア機能とはなにか？
- 4人の人が、同一のキーボードで対戦ができ、ゲームを正常に終了できること。

## 状態の遷移
1. ホーム
    - 画面には、スタートボタンと4人のニックネームを決める欄があるだけ。スタートボタンを押すと、トーナメント表が作られる。
2. トーナメント表の表示
    - 画面には対戦カードとトーナメント表が表示される。
    - 画面のトーナメント表にはこれまでの対戦成績が書かれている。
3. 次の試合の対戦カードの表示
    - 画面には次の試合の対戦カードが表示される。
4.  ゲーム開始
    - 画面はゲームを実行,描画する。
    - ゲームは１分で終了して得点の多いひとが勝ち。
5. ゲームの終了
    - 画面は、ゲームの勝敗を出力する。
    - 画面はゲームの開始画面に遷移するためのボタンがある。
    - 優勝者が決まっていないなら、2に戻る。
6. 優勝者の表示
    - 優勝者を称える画面を出す。
    - ホームに戻るボタンでホームに戻る。

## それぞれの画面で必要な機能
- ホーム画面
    - ゲームのタイトルの表示
    - 参加者ニックネームの入力欄
    - ゲームをスタートするボタン
- トーナメント表の表示画面
    - 参加者ニックネーム入りのトーナメント表の表示
- 次の試合の対戦カード表示画面
    - 対戦者の2人のニックネームの表示
- ゲームの画面
    - ゲームの残り時間の表示
    - 現在の両者の点数の表示
    - ゲームの描画
- ゲームの終了画面
    - 対戦者の名前の表示
    - 勝ち負けの表示
    - 点数差の表示
- 優勝者の表示画面
    - 優勝者の名前の表示

## どのように開発を進めるか？
- 概ねhtml, css, javascriptで開発できるため、viteを使う。

**Comment by ghost** [comment]
#16 でホームの作成は完了。

**Comment by ghost** [comment]
画面遷移専用pagesComponentを用意してもいいかも
