### ISSUE TITLE
volumeを消したときに、存在しないユーザーの認証が成功してしまう。

### ISSUE THREAD

**Issue by massahito** [ShotaTanemura/ft_transcendence#182]
## 問題
- volumeを消すと、ユーザーも消去されるが、そのユーザーの認証が成功してしまう
## 原因
- 以下のコードでtokenの認証を行っているが、その際、payload内のuuidの存在可否のみをチェックしており、そのuuidに対応するユーザーの存在可否についてはチェックしていない。
- そのためvolumeを削除した場合でも、 ブラウザに残っているjwtトークンは正常系なので認証に成功してしまう
https://github.com/ShotaTanemura/ft_transcendence/blob/8ad99f7768726fad43aa630d980958f5833c6d81/pong/pong/views/auth.py#L132-L150
## 対策
- 取り出したuuidにたいしてユーザーの存在可否を検証する

**Comment by ghost** [comment]
@ShotaTanemura さんから以下の点をご指摘いただき納得したためcloseします。
- セッションベース認証と比較して、トークンベース認証を使用するメリットに、dbへの問い合わせを減らすことがある
- 認証毎にdbに問い合わせるのはトークンベース認証のメリットを1つ消すことになる
- 代わりにjwt作成時の暗号化につかう秘密鍵を変更することで解決になるのでは？

これから、再構築を行う際は秘密鍵を新たに生成するようにする
