### ISSUE TITLE
MEETING kick-off meeting

### ISSUE THREAD

**Issue by ShotaTanemura** [ShotaTanemura/ft_transcendence#2]
### 目的:
  - 各メンバーの得意分野, 技術スタック, 興味関心の理解
  - subject.pdfに記載されている内容への理解度を合わせる
  - 次2週間の具体的行動とタスクの洗い出し
### 議題:

| topic | time |
| ------ | ------ |
| チェックイン | 5分 |
| subject.pdfの読み合わせ | 30分 |
|ドラッカー風エクササイズ | 40分 |
| 各メンバーの取り組みたいモジュール / 機能の洗い出し | 20分 |
| キャッチアップを実施する技術スタック/フレームワークの決定 | 20分 |
| 合計 | 120分 (休憩含む) |

### チェックイン (5分)
- 雑談

### subject.pdfの読み合わせ (30分)
- subject pdf: https://cdn.intra.42.fr/pdf/pdf/115767/en.subject.pdf

### ドラッカー風エクササイズ (40分)
- 参考1: https://agilewarrior.wordpress.com/2009/11/27/the-drucker-exercise/
- 参考2: https://www.agile-studio.jp/post/apm-drucker-excersize
- miro: https://miro.com/app/board/uXjVNgUMoyU=/

### 各メンバーの取り組みたいモジュール / 機能の洗い出し (20分)
- 取り組みたいモジュールをざっくり選ぶ

### キャッチアップを実施する技術スタック/フレームワークの決定 (20分)
- 次1週間で学びたい言語, フレームワーク, 参考資料を決定

### LOG
https://scrapbox.io/42-ft-transcendence/MTG1%E5%9B%9E%E7%9B%AE(3%2F16)_%E8%AD%B0%E4%BA%8B%E9%8C%B2

**Comment by subarunrun0812** [comment]
「各メンバーの取り組みたいモジュール」の際に、ペアプロのチームを決めたい。

**Comment by ShotaTanemura** [comment]
> 「各メンバーの取り組みたいモジュール」の際に、ペアプロのチームを決めたい。

次週からすぐ開発を始める予定ではないから、チーム決めは次週以降でも良い？
