### ISSUE TITLE
コードのリファクタリングを行う

### ISSUE THREAD

**Issue by massahito** [ShotaTanemura/ft_transcendence#21]
## 変数
- 基本的に全てにconstを使用。
- イテレートするさいはletを使用。
-  varは使用しない。
- snake_caseを使用する。
- 複数形と単数形を明確に区別する。

## 関数
- [A HC LC](https://github.com/kettanaito/naming-cheatsheet?tab=readme-ov-file#ahclc-pattern)に従って書く。
- do-whatの形式でかく。

## クラス
- 1コンポーネントに付き1ファイル。
- コンポーネントとそのファイル名はUpperCamelCaseで記述。

あとはあしたかく
## 参考文献
https://github.com/mitsuruog/javascript-style-guide/tree/master/react
https://github.com/kettanaito/naming-cheatsheet?tab=readme-ov-file#ahclc-pattern
https://github.com/airbnb/javascript

**Comment by ghost** [comment]
21-refactoring-react-pong-game-1 で終了
