### ISSUE TITLE
ReactをVanilla JSに変換する。

### ISSUE THREAD

**Issue by massahito** [ShotaTanemura/ft_transcendence#37]
## ReactからVanilla JSへの移行で考える点
1. コンポーネントで共有する変数をどのように実装するか？
2. ルーティングをどのように実装するか？
3. return内のcomponentや変数の埋め込みにどう対応するか？
4. return内のループにどう対応するか？
5. Hookをどのように実現するか？

**Comment by ghost** [comment]
1. routerに共通でアクセスできる変数をもたせる。
2. 毎回Componentを作成し、描画する。
3. appendChild, removeChildを使用してComponentのconstructorなどで追加、削除の処理をする。
4. 未検討
5. 未検討

**Comment by ghost** [comment]
不満点
- イベントハンドラはrenderしたあとに、再取得しないとrenderの際に消されてしまう。
- RoutingがConstructorが終了するまで使用できない。(setTimeout)を使用すると一応なんとかなる。
