### ISSUE TITLE
Realtime Pongの作成

### ISSUE THREAD

**Issue by massahito** [ShotaTanemura/ft_transcendence#48]
# 現状
Pong Gameのローカルマッチしかできない。
# 目標
Pong Gameのリモート対戦を可能にする。

# 画面遷移の流れ
1. ニックネームを入力する画面
2. room idを入力を入力する画面
3. roomに参加して、readyボタンを押す画面
4. readyボタンが押されたら、トーナメントを表示する画面
5. ゲーム画面(トーナメントが終了していない場合、4に戻る)
6. 優勝者を表彰する画面

# その他
- 一旦は同じroundでも一試合ずつ行い、プレイヤー以外は観戦させる。

**Comment by ghost** [comment]
1,2 はめんどくさいから一緒にやってしまう。
2に関してはルームをホストするのか、それとも参加するのかを選択するボタンがほしい。

**Comment by ghost** [comment]
## 今の現状
- ルート(/)に来たらnginxがrealtime-pong-game(中身は空)のリソースを返す。
- websocketのリクエストはrealtimeのconsumersが処理できるようにroutingする。
- Djangoのテンプレートをつかって、チャットルームを作成し、正しくwebsocketが動作していることを確認。

## 今からすること
- ルートに来た際に、nginxから返したリソースでwebsocketのルームに参加できるようにする。
- 人数の要件が満たされ全員がreadyになったら、ゲームをスタートさせる。
- あとの処理はvanilla-pong-gameと同じにする。

**Comment by ghost** [comment]
## 今の現状
- ルート(/)に来た際に、nginxから返したリソースでwebsocketのルームに参加できるようにした。

## 追加で必要な機能
- 各ユーザーにIDを割り振る。
- HostやGuestの概念を作る。
- Hostが人数やアクセスする人を制限する、必要ならパスワードもつける。

## 今後すること
- 人数の要件が満たされ全員がreadyになったら、ゲームをスタートさせる。
- あとの処理はvanilla-pong-gameと同じにする。

## DB設計
- user
    - ID (PK)
    - display name
- room
    - ID (PK)
    - roomID
    - winner
    - is_active
    - user (FK, Host)
    - 作成時期
    - 終了時期
- roomの参加者
    - user (CPK, FK)
    - room (CPK, FK)
- roomでの勝敗や試合情報
    - room (CPK, FK)
    - user1 (CPK, FK)
    - user2 (CPK, FK)
    - winner
    - 試合終了時間
    - score
    - round (トーナメントだとなくても良い)
 

## それぞれの段階で必要な処理
- Connect
    - hostならroomの作成 -> roomIDがすでに使われていた場合、エラー
    - guestならroomに追加 -> 人数が超過していたら場合、エラー
- ready(Recieve)
    - 全員がreadyになったらゲームスタート
- matchfinish(Recieve)
    - scoreを書き込む。(2人)
- Disconnect 
## 明日までの目標
- host, guestに分かれてユーザーがroomに参加でき、その情報をデータベースに保存できる。 

## そのた
websocketはclient側でtab切ったときに、oncloseイベントは走らない。しかしサーバー(channels)側ではdisconnectが走る。
どうやら、channlesにはgroup単位でデータを持つ機能はなさそう。
よってchannelsによってidを持たすことも難しそう。
そのユーザーがreadyかどうかをいちいちdbに書き込んでチェックしに行く処理をしたくない。

## 疑問
- websocketであってもmiddlewareにauthenticationを定義していたら、毎リクエスト時にちゃんと認証している？認証しているとしたら、途中で認証情報が一致しなくなった場合、どのような挙動をするのか？

**Comment by ghost** [comment]
roomを管理するconsumerとゲームのstateを管理するconsumerを分けたい。
consuemer同士で非同期通信できないか調べる。
roomのstateをみて、game-consumerが発火するでもいいかも

**Comment by ghost** [comment]
new issue作成のため、close
