### ISSUE TITLE
ビルドしたコンテナ上で動くDjangoサーバーからリクエストを取得できない

### ISSUE THREAD

**Issue by ShotaTanemura** [ShotaTanemura/ft_transcendence#66]
https://github.com/ShotaTanemura/ft_transcendence/blob/203e3fd7455029ff7e8c7da1f078d04913ce2e09/.devcontainer/requirements/Django/entrypoint.sh#L14 にて、以下のように書き直す必要がある

```py
    python manage.py runserver 0.0.0.0:8000
    exec gunicorn config.wsgi:application --bind 0.0.0.0:8000
```

**Comment by ShotaTanemura** [comment]
上記はDjangoサーバー立ち上げて外部からアクセス可能な状態にしているだけなので間違いでした
暑くて頭おかしなってました

**Comment by ShotaTanemura** [comment]
Nginx側ではすべてのリクエストをdjangoサーバーに流しており、djangoサーバー側ではどのパスにもマッチしないものにはindex.htmlを返していたことから、Nginx側で`/static`から始まるリクエストに対する処理を行う必要があった。そこで、Nginx側でdjango内の`pong`の`static`ディレクトリをマウントし、`/static`から始まるリクエストを別途ルーティングするようにしなければならない。

**Comment by ghost** [comment]
対応ありがとうございました。
