### ISSUE TITLE
linter or formatter 入れる

### ISSUE THREAD

**Issue by soooku** [ShotaTanemura/ft_transcendence#71]

**Comment by ShotaTanemura** [comment]
@soooku このイシューでGihub actionsにプロセスを導入するところまでやってほしいのでタスクとして以下の感じでお願い
- [ ] Pythonのlinterとformatterの候補をリストアップする (可能ならそれぞれの差別化要因も記載)
- [ ] 導入決定したlinter or formatterをGithub actionsのworkflowとして追加する
