### ISSUE TITLE
リアルタイムのpongゲームを作成

### ISSUE THREAD

**Issue by massahito** [ShotaTanemura/ft_transcendence#73]
# 現在の状態
- ローカルマッチしかできない
# 今回の目標
- リアルタイムマッチを可能にする。

**Comment by ghost** [comment]
websocketのやり取りは基本的にtext or binaryなのでやり取りはjsonをtextにdumpして行う。
```
{
    sender: "誰の情報か",
    type: "なんの情報か",
    contents: "どんな情報か",
}
```

基本的には以上のフォーマットに従ってやり取りをすることとする。

**Comment by ghost** [comment]
### やりたいこと
- 基本的にconsumerは接続役にしてlogicはRoomManagerとGameExecuter(仮名)に任せたい
- RoomManagerとGameExecuterはstateを管理して、次に接続先からの情報に対して取るアクションを変える

### RoomManager
#### Room State
- queuing (roomのparticipantsが１人以上だが、所定の人数が揃っていない状態)
- ready (roomに所定の人数は揃っているが、全てpartipantsのstateがreadyになっていない状態)
- matching (すべてのpartipantsがreadyになっていて、トーナメントを作成している状態)
- pending (次の試合のユーザーがreadyになっていない状態)
- in-game (ゲームが進行中の状態)
- finished (トーナメントが終了している状態)

#### Participants State
- not_in_place (readyではない状態)
- ready (readyな状態)
- in_game_1 (現在試合中のユーザー1)
- in_game_2 (現在試合中のユーザー2)
- loser (すでに敗退しているユーザー)
- winner (まだ勝ち上がっているユーザー)

### とるべきアクション (RoomManager)
- queuing
    - connectしたparticipantのstateをreadyをnot_in_placeにする
    - 全員のstateがnot_in_placeになったら、readyに変更する
- ready
    - participantsのキー入力によってparticipantのstateをreadyにする
    - 全員のstateがreadyになったら、トーナメントの作成する
- matching
    - トーナメントの表示を行っている時間。
    - すべてのユーザーが画面遷移を終了させた場合、roomのstateをpendingにする
- pending
   - 試合をするユーザーのキー入力をまつ
   - ２人ともreadyになったら、roomをin-gameにする
- in-game
   - 試合中のparticipantsのキー入力をGameExecuterに送る
   - gameから終了通知がきたら、結果をみてroomのstateをmatchingかfinishedにする
- finished
   - ユーザーのキー入力によってroomを廃棄する

### 積み残し
- GameExecuterからRoomManagerにゲームの終了をどのように通知するか？
   - GameExecuterを非同期で実行がいいかも
- クライアントサイドで自分がゲームのプレイヤーであることをどのように認識するか？
   - 自分の番に通知を入れる
